### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by zmingxie** [trailofbits/algo-ng#13]
I'm curious what the status is for this project... Are you still planning to re-write algo in terraform? Or is this idea abandoned now?

**Comment by jackivanov** [comment]
This is currently not being actively developed, but not abandoned. The project is opensource and currently in alpha, so any suggestions/PRs welcome. There's some security concerns regarding terraform usage and how they handle private keys in the TLS module, we'll be lookingfor a solution.

**Comment by zmingxie** [comment]
@jackivanov Thanks for sharing the status and your concerns around using Terraform for this setup. 

Frankly, your ansible version of `algo` works very well. Thank you very much for that btw! I'm looking into this only because I'm interested in terraform overall and trying to see if I can use it for wireguard setup too.

I'm going to close this issue now.
